# Generated by Django 5.0.1 on 2024-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0003_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
